source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"

# SỬA: Đã kích hoạt jbuilder để tạo JSON
gem "jbuilder"

# SỬA: Đã kích hoạt bcrypt cho việc Login (User model)
gem "bcrypt", "~> 3.1.7"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false

# SỬA: Đã kích hoạt image_processing cho Active Storage
gem "image_processing", "~> 1.2"

# SỬA: Đã kích hoạt rack-cors (BẮT BUỘC cho React API)
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end